import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Terms = () => (
  <div className="min-h-screen bg-background">
    <Navbar />
    <div className="pt-16">
      <section className="py-24 lg:py-32">
        <div className="max-w-[700px] mx-auto px-6 lg:px-12">
          <span className="font-mono-brand text-[10px] uppercase tracking-[0.2em] text-primary mb-4 block">Legal</span>
          <h1 className="text-[clamp(2rem,4vw,3.5rem)] font-medium leading-[0.9] tracking-[-0.04em] mb-12">
            Terms of Service
          </h1>

          <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">
            <div>
              <h2 className="font-display text-lg font-medium text-foreground mb-3">Acceptance</h2>
              <p>By using Echo, you agree to these terms. If you don't agree, please don't use our service. Simple as that.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-medium text-foreground mb-3">Your Content</h2>
              <p>You retain full ownership of all content you submit and all content generated by Echo from your submissions. We claim no intellectual property rights over your work.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-medium text-foreground mb-3">Acceptable Use</h2>
              <p>Echo is designed for legitimate content repurposing. You agree not to use the service for spam, plagiarism, or generating misleading content.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-medium text-foreground mb-3">Service Availability</h2>
              <p>We strive for 99.9% uptime but cannot guarantee uninterrupted service. We'll communicate any planned maintenance in advance.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-medium text-foreground mb-3">Billing</h2>
              <p>Paid plans are billed monthly. You can cancel anytime and retain access until the end of your billing period. No refunds for partial months.</p>
            </div>
            <p className="font-mono-brand text-[10px] text-muted-foreground/60 uppercase tracking-wider pt-4 border-t border-subtle">
              Last updated: March 2026
            </p>
          </div>
        </div>
      </section>
    </div>
    <Footer />
  </div>
);

export default Terms;
